version: '3.8'

services:
  cccc:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/root/config.yaml
      - ./logs:/root/logs
    environment:
      - GO_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/api/endpoints"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
